// Generated by scripts/gen-music-table.mjs: tracks from the owner's Pixabay downloads, re-encoded to 96 kbps.
// Pixabay Content License: free for commercial use, no attribution required.
import type { MusicTrack } from "@/types/project";

interface Row { file: string; tempoBpm: number | null; title: string; artist: string; genre: string; subgenre: string; moods: string[]; usage: "ad" | "guide"; energy: number; vocals: boolean; duration: number; added?: string }

const rows: Row[] = [
  {
    "file": "no-copyright-music-2026-piano-background-music-611657.mp3",
    "tempoBpm": null,
    "title": "Piano Background",
    "artist": "No Copyright Music",
    "genre": "Orchestral",
    "subgenre": "Piano Solo",
    "moods": [
      "Calm",
      "Warm"
    ],
    "usage": "guide",
    "energy": 3,
    "vocals": false,
    "duration": 175
  },
  {
    "file": "no-copyright-music-2026-corporate-background-611659.mp3",
    "tempoBpm": 80,
    "title": "Corporate Background",
    "artist": "No Copyright Music",
    "genre": "Electronic",
    "subgenre": "Chillout",
    "moods": [
      "Modern",
      "Calm"
    ],
    "usage": "guide",
    "energy": 4,
    "vocals": false,
    "duration": 179
  },
  {
    "file": "kiravale-background-music-for-video-593669.mp3",
    "tempoBpm": 97,
    "title": "Background for Video",
    "artist": "Kiravale",
    "genre": "Cinematic",
    "subgenre": "Inspirational",
    "moods": [
      "Calm",
      "Modern"
    ],
    "usage": "guide",
    "energy": 4,
    "vocals": false,
    "duration": 114
  },
  {
    "file": "gr0za-background-music-background-610368.mp3",
    "tempoBpm": 125,
    "title": "Soft Background",
    "artist": "Gr0za",
    "genre": "Electronic",
    "subgenre": "Ambient",
    "moods": [
      "Calm",
      "Modern"
    ],
    "usage": "guide",
    "energy": 3,
    "vocals": false,
    "duration": 113
  },
  {
    "file": "verclub_music-timelapse-background-609007.mp3",
    "tempoBpm": 100,
    "title": "Timelapse Background",
    "artist": "Verclub Music",
    "genre": "Electronic",
    "subgenre": "Ambient",
    "moods": [
      "Calm",
      "Quiet"
    ],
    "usage": "guide",
    "energy": 3,
    "vocals": false,
    "duration": 180
  },
  {
    "file": "folk_tales-calm-carefree_56sec-610080.mp3",
    "tempoBpm": 90,
    "title": "Calm Carefree (56 s)",
    "artist": "Folk Tales",
    "genre": "Acoustic / Folk",
    "subgenre": "Acoustic",
    "moods": [
      "Calm",
      "Warm"
    ],
    "usage": "guide",
    "energy": 3,
    "vocals": false,
    "duration": 56
  },
  {
    "file": "folk_tales-calm-carefree_22sec-610084.mp3",
    "tempoBpm": null,
    "title": "Calm Carefree (22 s)",
    "artist": "Folk Tales",
    "genre": "Acoustic / Folk",
    "subgenre": "Acoustic",
    "moods": [
      "Calm",
      "Warm"
    ],
    "usage": "guide",
    "energy": 3,
    "vocals": false,
    "duration": 22
  },
  {
    "file": "folk_tales-calm-carefree_12sec-610085.mp3",
    "tempoBpm": null,
    "title": "Calm Carefree (12 s)",
    "artist": "Folk Tales",
    "genre": "Acoustic / Folk",
    "subgenre": "Acoustic",
    "moods": [
      "Calm",
      "Warm"
    ],
    "usage": "guide",
    "energy": 3,
    "vocals": false,
    "duration": 12
  },
  {
    "file": "folk_tales-beautiful-beautiful-things_60sec-610064.mp3",
    "tempoBpm": 120,
    "title": "Beautiful Things",
    "artist": "Folk Tales",
    "genre": "Acoustic / Folk",
    "subgenre": "Acoustic",
    "moods": [
      "Warm",
      "Calm"
    ],
    "usage": "guide",
    "energy": 3,
    "vocals": false,
    "duration": 60
  },
  {
    "file": "no-copyright-music-2026-emotional-cello-611670.mp3",
    "tempoBpm": null,
    "title": "Emotional Cello",
    "artist": "No Copyright Music",
    "genre": "Cinematic",
    "subgenre": "Emotional",
    "moods": [
      "Emotional",
      "Calm"
    ],
    "usage": "guide",
    "energy": 3,
    "vocals": false,
    "duration": 180
  },
  {
    "file": "leberch-film-underscore-254392.mp3",
    "tempoBpm": 103,
    "title": "Film Underscore",
    "artist": "Leberch",
    "genre": "Cinematic",
    "subgenre": "Drama Underscore",
    "moods": [
      "Cinematic",
      "Calm"
    ],
    "usage": "guide",
    "energy": 3,
    "vocals": false,
    "duration": 137
  },
  {
    "file": "smooth-fade-out.mp3",
    "tempoBpm": null,
    "title": "Smooth Fade Out",
    "artist": "Scorvik Library",
    "genre": "Electronic",
    "subgenre": "Ambient",
    "moods": [
      "Calm",
      "Quiet"
    ],
    "usage": "guide",
    "energy": 2,
    "vocals": false,
    "duration": 88
  },
  {
    "file": "smooth-fade-out-2.mp3",
    "tempoBpm": null,
    "title": "Smooth Fade Out II",
    "artist": "Scorvik Library",
    "genre": "Electronic",
    "subgenre": "Ambient",
    "moods": [
      "Calm",
      "Quiet"
    ],
    "usage": "guide",
    "energy": 2,
    "vocals": false,
    "duration": 82
  },
  {
    "file": "alex-morgan-blues-jazz-coffee-shop-552788.mp3",
    "tempoBpm": 84,
    "title": "Blues Jazz Coffee Shop",
    "artist": "Alex Morgan",
    "genre": "Jazz",
    "subgenre": "Jazz Blues",
    "moods": [
      "Blues",
      "Warm"
    ],
    "usage": "guide",
    "energy": 3,
    "vocals": false,
    "duration": 162
  },
  {
    "file": "alex-morgan-blues-jazz-sunny-cafe-552795.mp3",
    "tempoBpm": null,
    "title": "Blues Jazz Sunny Café",
    "artist": "Alex Morgan",
    "genre": "Jazz",
    "subgenre": "Jazz Blues",
    "moods": [
      "Blues",
      "Warm"
    ],
    "usage": "guide",
    "energy": 3,
    "vocals": false,
    "duration": 180
  },
  {
    "file": "alex-morgan-blues-jazz-restaurant-552796.mp3",
    "tempoBpm": null,
    "title": "Blues Jazz Restaurant",
    "artist": "Alex Morgan",
    "genre": "Jazz",
    "subgenre": "Jazz Blues",
    "moods": [
      "Blues",
      "Warm"
    ],
    "usage": "ad",
    "energy": 4,
    "vocals": false,
    "duration": 180
  },
  {
    "file": "alec_koff-blues-ballad-487408.mp3",
    "tempoBpm": null,
    "title": "Blues Ballad",
    "artist": "Alec Koff",
    "genre": "Blues",
    "subgenre": "Slow Blues",
    "moods": [
      "Blues",
      "Calm",
      "Emotional"
    ],
    "usage": "guide",
    "energy": 3,
    "vocals": false,
    "duration": 152
  },
  {
    "file": "aurec-blues-587560.mp3",
    "tempoBpm": null,
    "title": "Blues",
    "artist": "Aurec",
    "genre": "Blues",
    "subgenre": "Chicago Blues",
    "moods": [
      "Blues",
      "Authentic"
    ],
    "usage": "ad",
    "energy": 5,
    "vocals": false,
    "duration": 180
  },
  {
    "file": "shwarzborg-delta-blues-387901.mp3",
    "tempoBpm": null,
    "title": "Delta Blues",
    "artist": "Shwarzborg",
    "genre": "Blues",
    "subgenre": "Delta Blues",
    "moods": [
      "Blues",
      "Authentic"
    ],
    "usage": "ad",
    "energy": 5,
    "vocals": false,
    "duration": 155
  },
  {
    "file": "nickpanek-blues-rock-instrumental-69-259289.mp3",
    "tempoBpm": null,
    "title": "Blues Rock Instrumental",
    "artist": "Nick Panek",
    "genre": "Blues",
    "subgenre": "Blues Rock",
    "moods": [
      "Blues",
      "Bold"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 134
  },
  {
    "file": "nickpanek-cat-on-the-porch-rock-blues-instrumental-275925.mp3",
    "tempoBpm": 92,
    "title": "Cat on the Porch",
    "artist": "Nick Panek",
    "genre": "Blues",
    "subgenre": "Blues Rock",
    "moods": [
      "Blues",
      "Warm"
    ],
    "usage": "ad",
    "energy": 5,
    "vocals": false,
    "duration": 113
  },
  {
    "file": "nickpanek-kansas-blues-blues-rock-instrumental-259874.mp3",
    "tempoBpm": null,
    "title": "Kansas Blues",
    "artist": "Nick Panek",
    "genre": "Blues",
    "subgenre": "Blues Rock",
    "moods": [
      "Blues",
      "Bold"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 149
  },
  {
    "file": "tablues.mp3",
    "tempoBpm": 120,
    "title": "Tablues",
    "artist": "Scorvik Library",
    "genre": "Blues",
    "subgenre": "Texas Blues",
    "moods": [
      "Blues"
    ],
    "usage": "ad",
    "energy": 5,
    "vocals": false,
    "duration": 16
  },
  {
    "file": "35285074-reconsider-baby-145892.mp3",
    "tempoBpm": 85,
    "title": "Reconsider Baby",
    "artist": "Pixabay",
    "genre": "Blues",
    "subgenre": "Slow Blues",
    "moods": [
      "Blues",
      "Emotional"
    ],
    "usage": "ad",
    "energy": 4,
    "vocals": true,
    "duration": 180
  },
  {
    "file": "alex-morgan-movie-wide-screen-panorama-578501.mp3",
    "tempoBpm": null,
    "title": "Wide Screen Panorama",
    "artist": "Alex Morgan",
    "genre": "Cinematic",
    "subgenre": "Epic",
    "moods": [
      "Cinematic",
      "Emotional"
    ],
    "usage": "ad",
    "energy": 5,
    "vocals": false,
    "duration": 180
  },
  {
    "file": "leberch-film-594952.mp3",
    "tempoBpm": null,
    "title": "Film",
    "artist": "Leberch",
    "genre": "Cinematic",
    "subgenre": "Epic",
    "moods": [
      "Cinematic",
      "Bold"
    ],
    "usage": "ad",
    "energy": 5,
    "vocals": false,
    "duration": 96
  },
  {
    "file": "the_mountain-film-591388.mp3",
    "tempoBpm": null,
    "title": "Film",
    "artist": "The Mountain",
    "genre": "Cinematic",
    "subgenre": "Epic",
    "moods": [
      "Cinematic",
      "Adventurous"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 126
  },
  {
    "file": "no-copyright-music-2026-inspiring-611650.mp3",
    "tempoBpm": null,
    "title": "Inspiring",
    "artist": "No Copyright Music",
    "genre": "Cinematic",
    "subgenre": "Inspirational",
    "moods": [
      "Emotional",
      "Bright"
    ],
    "usage": "ad",
    "energy": 5,
    "vocals": false,
    "duration": 168
  },
  {
    "file": "lnplusmusic-motivation-motivation-music-611031.mp3",
    "tempoBpm": 104,
    "title": "Motivation",
    "artist": "LN Plus Music",
    "genre": "Cinematic",
    "subgenre": "Inspirational",
    "moods": [
      "Energetic",
      "Bold"
    ],
    "usage": "ad",
    "energy": 7,
    "vocals": false,
    "duration": 137
  },
  {
    "file": "lnplusmusic-advertising-advertising-music-610971.mp3",
    "tempoBpm": 145,
    "title": "Advertising",
    "artist": "LN Plus Music",
    "genre": "Electronic",
    "subgenre": "Electropop",
    "moods": [
      "Bright",
      "Modern"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 148
  },
  {
    "file": "lnplusmusic-product-product-launch-611921.mp3",
    "tempoBpm": 100,
    "title": "Product Launch",
    "artist": "LN Plus Music",
    "genre": "Electronic",
    "subgenre": "Electropop",
    "moods": [
      "Modern",
      "Bold"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 118
  },
  {
    "file": "lnplusmusic-happy-happy-music-611028.mp3",
    "tempoBpm": 108,
    "title": "Happy",
    "artist": "LN Plus Music",
    "genre": "Electronic",
    "subgenre": "Electropop",
    "moods": [
      "Playful",
      "Bright"
    ],
    "usage": "ad",
    "energy": 7,
    "vocals": false,
    "duration": 107
  },
  {
    "file": "lnplusmusic-event-event-music-611920.mp3",
    "tempoBpm": 137,
    "title": "Event",
    "artist": "LN Plus Music",
    "genre": "Electronic",
    "subgenre": "Electropop",
    "moods": [
      "Energetic",
      "Bright"
    ],
    "usage": "ad",
    "energy": 7,
    "vocals": false,
    "duration": 52
  },
  {
    "file": "no-copyright-music-2026-corporate-611644.mp3",
    "tempoBpm": 146,
    "title": "Corporate",
    "artist": "No Copyright Music",
    "genre": "Electronic",
    "subgenre": "Chillout",
    "moods": [
      "Modern",
      "Bold"
    ],
    "usage": "ad",
    "energy": 5,
    "vocals": false,
    "duration": 141
  },
  {
    "file": "no-copyright-music-2026-corporate-corporate-music-611643.mp3",
    "tempoBpm": 160,
    "title": "Corporate Music",
    "artist": "No Copyright Music",
    "genre": "Electronic",
    "subgenre": "Chillout",
    "moods": [
      "Modern",
      "Bright"
    ],
    "usage": "ad",
    "energy": 5,
    "vocals": false,
    "duration": 125
  },
  {
    "file": "gr0za-upbeat-upbeat-music-610413.mp3",
    "tempoBpm": 120,
    "title": "Upbeat",
    "artist": "Gr0za",
    "genre": "Electronic",
    "subgenre": "Electropop",
    "moods": [
      "Playful",
      "Bright"
    ],
    "usage": "ad",
    "energy": 7,
    "vocals": false,
    "duration": 130
  },
  {
    "file": "lnplusmusic-travel-travel-music-611925.mp3",
    "tempoBpm": 118,
    "title": "Travel",
    "artist": "LN Plus Music",
    "genre": "World",
    "subgenre": "Tropical",
    "moods": [
      "Adventurous",
      "Bright"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 118
  },
  {
    "file": "lnplusmusic-indian-indian-music-611803.mp3",
    "tempoBpm": 107,
    "title": "Indian",
    "artist": "LN Plus Music",
    "genre": "World",
    "subgenre": "World Fusion",
    "moods": [
      "Adventurous",
      "Warm"
    ],
    "usage": "ad",
    "energy": 5,
    "vocals": false,
    "duration": 80
  },
  {
    "file": "folk_tales-country-countryside_67sec-610096.mp3",
    "tempoBpm": 100,
    "title": "Countryside (67 s)",
    "artist": "Folk Tales",
    "genre": "Acoustic / Folk",
    "subgenre": "Country",
    "moods": [
      "Warm",
      "Authentic"
    ],
    "usage": "ad",
    "energy": 4,
    "vocals": false,
    "duration": 67
  },
  {
    "file": "folk_tales-country-countryside_51sec-610098.mp3",
    "tempoBpm": 100,
    "title": "Countryside (51 s)",
    "artist": "Folk Tales",
    "genre": "Acoustic / Folk",
    "subgenre": "Country",
    "moods": [
      "Warm",
      "Authentic"
    ],
    "usage": "ad",
    "energy": 4,
    "vocals": false,
    "duration": 51
  },
  {
    "file": "folk_tales-country-countryside_41sec-610099.mp3",
    "tempoBpm": 100,
    "title": "Countryside (41 s)",
    "artist": "Folk Tales",
    "genre": "Acoustic / Folk",
    "subgenre": "Country",
    "moods": [
      "Warm",
      "Authentic"
    ],
    "usage": "ad",
    "energy": 4,
    "vocals": false,
    "duration": 41
  },
  {
    "file": "gr0za-racing-racing-music-610347.mp3",
    "tempoBpm": 100,
    "title": "Racing",
    "artist": "Gr0za",
    "genre": "Electronic",
    "subgenre": "Electropop",
    "moods": [
      "Drive",
      "Energetic"
    ],
    "usage": "ad",
    "energy": 8,
    "vocals": false,
    "duration": 145
  },
  {
    "file": "lnplusmusic-car-car-music-611883.mp3",
    "tempoBpm": 117,
    "title": "Car",
    "artist": "LN Plus Music",
    "genre": "Electronic",
    "subgenre": "Electropop",
    "moods": [
      "Drive",
      "Energetic"
    ],
    "usage": "ad",
    "energy": 7,
    "vocals": false,
    "duration": 104
  },
  {
    "file": "lnplusmusic-driving-car-automotive-music-611929.mp3",
    "tempoBpm": 80,
    "title": "Driving Automotive",
    "artist": "LN Plus Music",
    "genre": "Electronic",
    "subgenre": "Electropop",
    "moods": [
      "Drive",
      "Bold"
    ],
    "usage": "ad",
    "energy": 7,
    "vocals": false,
    "duration": 100
  },
  {
    "file": "lnplusmusic-funk-funk-music-611911.mp3",
    "tempoBpm": 76,
    "title": "Funk",
    "artist": "LN Plus Music",
    "genre": "Soul / R&B",
    "subgenre": "Funk",
    "moods": [
      "Playful",
      "Bold"
    ],
    "usage": "ad",
    "energy": 7,
    "vocals": false,
    "duration": 110
  },
  {
    "file": "jonasblakewood-rock-rock-music-611689.mp3",
    "tempoBpm": 80,
    "title": "Rock",
    "artist": "Jonas Blakewood",
    "genre": "Rock",
    "subgenre": "Classic Rock",
    "moods": [
      "Drive",
      "Bold"
    ],
    "usage": "ad",
    "energy": 7,
    "vocals": false,
    "duration": 72
  },
  {
    "file": "jonasblakewood-rock-upbeat-611688.mp3",
    "tempoBpm": null,
    "title": "Rock Upbeat",
    "artist": "Jonas Blakewood",
    "genre": "Rock",
    "subgenre": "Classic Rock",
    "moods": [
      "Drive",
      "Energetic"
    ],
    "usage": "ad",
    "energy": 8,
    "vocals": false,
    "duration": 18
  },
  {
    "file": "lnplusmusic-rap-rap-beat-611918.mp3",
    "tempoBpm": 107,
    "title": "Rap Beat",
    "artist": "LN Plus Music",
    "genre": "Hip-Hop",
    "subgenre": "Boom Bap",
    "moods": [
      "Bold",
      "Energetic"
    ],
    "usage": "ad",
    "energy": 7,
    "vocals": false,
    "duration": 128
  },
  {
    "file": "gr0za-trap-trap-beat-610220.mp3",
    "tempoBpm": 150,
    "title": "Trap Beat",
    "artist": "Gr0za",
    "genre": "Hip-Hop",
    "subgenre": "Trap",
    "moods": [
      "Bold",
      "Energetic"
    ],
    "usage": "ad",
    "energy": 8,
    "vocals": false,
    "duration": 137
  },
  {
    "file": "no-copyright-music-2026-hip-hop-hip-hop-beat-611663.mp3",
    "tempoBpm": 150,
    "title": "Hip-Hop Beat",
    "artist": "No Copyright Music",
    "genre": "Hip-Hop",
    "subgenre": "Boom Bap",
    "moods": [
      "Bold",
      "Modern"
    ],
    "usage": "ad",
    "energy": 7,
    "vocals": false,
    "duration": 177
  },
  {
    "file": "apalonbeats-promo-promotional-showreel-music-540564.mp3",
    "tempoBpm": 137,
    "title": "Promotional Showreel",
    "artist": "Apalon Beats",
    "genre": "Electronic",
    "subgenre": "Corporate",
    "moods": [
      "Modern",
      "Bright"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 116,
    "added": "2026-10-08"
  },
  {
    "file": "atlasaudio-cinematic-adventure-610029.mp3",
    "tempoBpm": null,
    "title": "Cinematic Adventure",
    "artist": "Atlas Audio",
    "genre": "Cinematic",
    "subgenre": "Adventure",
    "moods": [
      "Cinematic",
      "Adventurous"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 120,
    "added": "2026-10-08"
  },
  {
    "file": "atlasaudio-cinematic-motivation-606227.mp3",
    "tempoBpm": 79,
    "title": "Cinematic Motivation",
    "artist": "Atlas Audio",
    "genre": "Cinematic",
    "subgenre": "Inspirational",
    "moods": [
      "Emotional",
      "Bold"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 110,
    "added": "2026-10-08"
  },
  {
    "file": "atlasaudio-promo-promo-music-576651.mp3",
    "tempoBpm": 122,
    "title": "Promo Music",
    "artist": "Atlas Audio",
    "genre": "Electronic",
    "subgenre": "Corporate",
    "moods": [
      "Modern",
      "Bold"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 114,
    "added": "2026-10-08"
  },
  {
    "file": "bombinsound-promo-promo-music-version-2-560477.mp3",
    "tempoBpm": 92,
    "title": "Promo Music (v2)",
    "artist": "Bombin Sound",
    "genre": "Electronic",
    "subgenre": "Corporate",
    "moods": [
      "Modern",
      "Bright"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 102,
    "added": "2026-10-08"
  },
  {
    "file": "bombinsound-promo-promo-music-version-4-560475.mp3",
    "tempoBpm": 92,
    "title": "Promo Music (v4)",
    "artist": "Bombin Sound",
    "genre": "Electronic",
    "subgenre": "Corporate",
    "moods": [
      "Modern",
      "Bright"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 78,
    "added": "2026-10-08"
  },
  {
    "file": "bombinsound-promo-promo-music-version-5-560474.mp3",
    "tempoBpm": 92,
    "title": "Promo Music (v5)",
    "artist": "Bombin Sound",
    "genre": "Electronic",
    "subgenre": "Corporate",
    "moods": [
      "Modern",
      "Bright"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 52,
    "added": "2026-10-08"
  },
  {
    "file": "bombinsound-promo-promo-music-version-7-560472.mp3",
    "tempoBpm": 92,
    "title": "Promo Music (v7)",
    "artist": "Bombin Sound",
    "genre": "Electronic",
    "subgenre": "Corporate",
    "moods": [
      "Modern",
      "Bright"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 26,
    "added": "2026-10-08"
  },
  {
    "file": "gr0za-promo-promo-music-573355.mp3",
    "tempoBpm": null,
    "title": "Promo Music A",
    "artist": "Gr0za",
    "genre": "Electronic",
    "subgenre": "Corporate",
    "moods": [
      "Modern",
      "Bold"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 129,
    "added": "2026-10-08"
  },
  {
    "file": "gr0za-promo-promo-music-596446.mp3",
    "tempoBpm": null,
    "title": "Promo Music B",
    "artist": "Gr0za",
    "genre": "Electronic",
    "subgenre": "Corporate",
    "moods": [
      "Modern",
      "Bold"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 132,
    "added": "2026-10-08"
  },
  {
    "file": "gr0za-promo-promo-music-609223.mp3",
    "tempoBpm": null,
    "title": "Promo Music C",
    "artist": "Gr0za",
    "genre": "Electronic",
    "subgenre": "Corporate",
    "moods": [
      "Modern",
      "Bold"
    ],
    "usage": "ad",
    "energy": 7,
    "vocals": false,
    "duration": 137,
    "added": "2026-10-08"
  },
  {
    "file": "jonasblakewood-promo-promo-music-567324.mp3",
    "tempoBpm": 80,
    "title": "Promo Music",
    "artist": "Jonas Blakewood",
    "genre": "Electronic",
    "subgenre": "Corporate",
    "moods": [
      "Bold",
      "Energetic"
    ],
    "usage": "ad",
    "energy": 7,
    "vocals": false,
    "duration": 180,
    "added": "2026-10-08"
  },
  {
    "file": "mondamusic-promo-promotional-showreel-music-512831.mp3",
    "tempoBpm": 80,
    "title": "Promotional Showreel",
    "artist": "Monda Music",
    "genre": "Electronic",
    "subgenre": "Corporate",
    "moods": [
      "Modern",
      "Bright"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 66,
    "added": "2026-10-08"
  },
  {
    "file": "kulakovka-fashion-session-566503.mp3",
    "tempoBpm": 123,
    "title": "Fashion Session",
    "artist": "Kulakovka",
    "genre": "Electronic",
    "subgenre": "House",
    "moods": [
      "Modern",
      "Playful"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": false,
    "duration": 162,
    "added": "2026-10-08"
  },
  {
    "file": "mildrelaxation-believe-in-miracle-by-prabajithk-121041.mp3",
    "tempoBpm": null,
    "title": "Believe in Miracle",
    "artist": "Prabajith K",
    "genre": "Cinematic",
    "subgenre": "Ambient",
    "moods": [
      "Emotional",
      "Calm"
    ],
    "usage": "guide",
    "energy": 3,
    "vocals": false,
    "duration": 122,
    "added": "2026-10-08"
  },
  {
    "file": "jakob_welik-bla-bla-radio-edit-550257.mp3",
    "tempoBpm": 150,
    "title": "Bla Bla (Radio Edit)",
    "artist": "Jakob Welik",
    "genre": "Pop",
    "subgenre": "Radio Edit",
    "moods": [
      "Playful",
      "Bright"
    ],
    "usage": "ad",
    "energy": 6,
    "vocals": true,
    "duration": 157,
    "added": "2026-10-08"
  },
  {
    "file": "jakob_welik-das-leuchtturmfest-am-ende-des-meeres-550256.mp3",
    "tempoBpm": null,
    "title": "Das Leuchtturmfest am Ende des Meeres",
    "artist": "Jakob Welik",
    "genre": "Pop",
    "subgenre": "Song",
    "moods": [
      "Emotional",
      "Warm"
    ],
    "usage": "ad",
    "energy": 4,
    "vocals": true,
    "duration": 180,
    "added": "2026-10-08"
  }
];

export const pixabayMusic: MusicTrack[] = rows.map((row): MusicTrack => ({
  id: row.file.replace(/\.mp3$/, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""),
  title: row.title,
  artist: row.artist,
  source: "Pixabay Music",
  sourceType: "pixabay",
  sourceUrl: "https://pixabay.com/music/",
  audioUrl: `/api/music/${row.file}`,
  duration: row.duration,
  genre: row.genre,
  subgenre: row.subgenre,
  style: [row.subgenre],
  mood: row.moods,
  tags: [...row.moods, row.genre, row.subgenre],
  energy: row.energy,
  tempoBpm: row.tempoBpm,
  instrumentation: [],
  era: "Contemporary",
  vocals: row.vocals,
  instrumental: !row.vocals,
  useCases: [row.usage === "ad" ? "Ad" : "Guide"],
  usage: row.usage,
  voiceoverSuitable: !row.vocals,
  language: null,
  brandFit: [],
  commercialUse: true,
  metadataStatus: "verified",
  allowedPlatforms: ["youtube", "instagram", "facebook", "tiktok", "square-social"],
  licenseType: "Pixabay Content License (free commercial use)",
  attributionRequired: false,
  licenseUrl: "https://pixabay.com/service/license-summary/",
  downloadedAt: row.added ?? "2026-10-05",
  licenseCheckedAt: row.added ?? "2026-10-07",
}));
