import Link from "next/link";
import { LandingWorkbench } from "@/components/landing-workbench";

const steps = [
  ["01", "Start with a URL", "One link is enough. We look for the details that make the site yours."],
  ["02", "Shape the story", "A first storyboard, drawn from your pages, products and point of view."],
  ["03", "Make it yours", "Refine the scenes, set your format and create a video ready to share."],
];

export function LandingPage() {
  return (
    <div className="landing">
      <section className="hero">
        <div className="hero-copy">
          <span className="eyebrow">A creative studio for the open web</span>
          <h1>Make your<br />website a <span>film.</span></h1>
          <p>Your website already holds the story. SCORVIK finds it, shapes the scenes and composes a film around your point of view.</p>
          <div className="hero-cta"><Link href="/create" className="button">START A PRODUCTION <span aria-hidden="true">↗</span></Link><a href="#how-it-works" className="button button-light">Explore the process</a></div>
          <div className="hero-note"><span>WEBSITE → STORY → FILM</span><span>YOUR BRAND, IN FRAME</span></div>
        </div>
        <LandingWorkbench />
      </section>
      <div className="proof-strip" aria-label="Product principles"><div className="proof-item"><b>01</b>Built from your website</div><div className="proof-item"><b>02</b>Storyboard before render</div><div className="proof-item"><b>03</b>Made for every format</div><div className="proof-item"><b>04</b>Your voice, your brand</div></div>
      <section className="section" id="how-it-works"><div className="section-heading"><span className="eyebrow">From website to finished video</span><h2>Your website is already the creative brief.</h2><p>SCORVIK connects the dots between what you do and the way the world should see it.</p></div><div className="steps">{steps.map(([number, title, copy]) => <article className="step" key={number}><span className="step-no">{number} / 03</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
      <section className="section showcase"><div className="section-heading"><span className="eyebrow">The story, in your hands</span><h2>A storyboard you can actually shape.</h2><p>See the sequence before a frame is rendered. Reorder scenes, refine the words and choose the feeling of the final film.</p><Link className="text-link showcase-link" href="/create">Build a storyboard <span aria-hidden="true">→</span></Link></div><div className="showcase-board" aria-hidden="true"><div className="board-top"><span>NORTHLINE.STUDIO / STORYBOARD</span><span>00:30 · 16:9</span></div><div className="board-scenes"><div className="board-scene">01 / HOOK</div><div className="board-scene">02 / STORY</div><div className="board-scene">03 / PRODUCT</div></div><div className="board-timeline"><i /><i /><i /></div></div></section>
      <section className="section format-section"><div className="section-heading"><span className="eyebrow">Made for where it goes</span><h2>One story. The right frame for every feed.</h2><p>Choose the shape before the first cut, then keep your message composed for the platform.</p></div><div className="format-showcase"><div className="format-copy"><div><b>16:9</b><span>Landscape · YouTube, web</span></div><div><b>9:16</b><span>Portrait · Reels, Shorts</span></div><div><b>1:1</b><span>Square · Social, product</span></div><div><b>4:5</b><span>Portrait · Feed placements</span></div></div><div className="format-frames" aria-hidden="true"><div className="format-frame landscape"><span>YOUR STORY / 16:9</span></div><div className="format-frame portrait"><span>YOUR STORY / 9:16</span></div><div className="format-frame square"><span>YOUR STORY / 1:1</span></div></div></div></section>
      <section className="section versions-section"><div className="versions-copy"><span className="eyebrow">More than one way to say it</span><h2>Find the version that feels like you.</h2><p>Change the hook, pacing, voice or call to action. Keep the same source, explore a different point of view.</p><Link href="/create" className="button button-light">Shape a first cut <span aria-hidden="true">→</span></Link></div><div className="version-list"><div><span>01</span><b>Considered, never overdone</b><small>EDITORIAL · WARM VOICE</small></div><div><span>02</span><b>Made to stop the scroll</b><small>ENERGETIC · QUICKER PACE</small></div><div><span>03</span><b>Every detail, in focus</b><small>PRODUCT-LED · MINIMAL</small></div></div></section>
      <section className="section usecase-section"><div className="section-heading"><span className="eyebrow">For the people behind the URL</span><h2>Small team or full studio. Start with what you’ve made.</h2></div><div className="usecase-list"><span>Independent brands</span><span>Marketing teams</span><span>Creative agencies</span><span>Ecommerce</span><span>SaaS products</span><span>Creators & studios</span></div></section>
      <section className="section library-section"><div className="library-copy"><span className="eyebrow">Every version, in one place</span><h2>A creative library, not a job queue.</h2><p>Keep each project, its storyboard and every variation close at hand.</p><Link href="/projects" className="text-link showcase-link">Visit the project library →</Link></div><div className="library-preview"><div className="library-preview-head"><span>RECENT PROJECTS</span><span>VIEW ALL ↗</span></div><div className="library-row"><i className="library-thumb"/><span><b>Northline — brand film</b><small>northline.studio</small></span><em>30s · 16:9</em></div><div className="library-row"><i className="library-thumb second"/><span><b>Quietform — product story</b><small>quietform.co</small></span><em>15s · 9:16</em></div></div></section>
      <section className="section faq-section"><div className="section-heading"><span className="eyebrow">A few useful details</span><h2>Before you begin.</h2></div><div className="faq-list"><details><summary>What does SCORVIK use to make the story?</summary><p>It uses the content, imagery and brand cues found on a website to draft a storyboard. In this demo, that analysis is represented with sample data.</p></details><details><summary>Can I change the storyboard before rendering?</summary><p>Yes. Reorder, duplicate or remove scenes, adjust timing and refine headlines, supporting copy, voiceover, visuals and transitions.</p></details><details><summary>Does the demo create an MP4?</summary><p>Not yet. The render step creates a saved project preview with a JSON project download. A real render provider can be connected behind the provider interfaces.</p></details><details><summary>Where are my projects saved?</summary><p>Projects are saved in this browser’s local storage and remain on this device and browser profile.</p></details></div></section>
      <section className="section pricing-strip"><div><span className="eyebrow">Try the whole creation flow</span><h2>Start with the first cut.</h2><p>Explore the local demo without an account or API key.</p></div><Link href="/pricing" className="button button-light">Explore demo pricing <span aria-hidden="true">→</span></Link></section>
      <section className="section closing"><div><span className="eyebrow">Make the first frame</span><h2>Your next great video is already on your website.</h2></div><Link href="/create" className="button button-lime">Create your first video <span aria-hidden="true">↗</span></Link></section>
      <footer className="footer"><Link className="brand" href="/"><span className="brand-mark" aria-hidden="true">S</span><span>SCORVIK</span></Link><span>From website to finished video.</span><Link href="/projects">Project library →</Link></footer>
    </div>
  );
}
