import Link from "next/link";
import { LandingWorkbench } from "@/components/landing-workbench";

const steps = [
  ["01", "Start with your website", "Share a link and we'll find the details that make your brand yours."],
  ["02", "Shape the story", "We'll bring the best pieces together. You decide what stays."],
  ["03", "Make it yours", "Choose a feeling, a voice and a place to share your film."],
];

export function LandingPage() {
  return (
    <div className="landing">
      <section className="hero">
        <div className="hero-copy">
          <span className="eyebrow">A creative studio for the open web</span>
          <h1>Make your<br />website a <span>film.</span></h1>
          <p>Your website already holds the story. SCORVIK helps you find it, shape it and bring it to life as a film.</p>
          <div className="hero-cta"><Link href="/create" className="button">START WITH YOUR WEBSITE <span aria-hidden="true">↗</span></Link><a href="#how-it-works" className="button button-light">See how it works</a></div>
          <div className="hero-note"><span>WEBSITE → STORY → FILM</span><span>YOUR STORY, YOUR WAY</span></div>
        </div>
        <LandingWorkbench />
      </section>
      <div className="proof-strip" aria-label="What you can shape"><div className="proof-item"><b>01</b>Start with your website</div><div className="proof-item"><b>02</b>Make the story yours</div><div className="proof-item"><b>03</b>Choose where it belongs</div><div className="proof-item"><b>04</b>Find your voice and sound</div></div>
      <section className="section" id="how-it-works"><div className="section-heading"><span className="eyebrow">A little help along the way</span><h2>Your story is already there.</h2><p>SCORVIK helps you bring the right details together and turn them into a film that feels like you.</p></div><div className="steps">{steps.map(([number, title, copy]) => <article className="step" key={number}><span className="step-no">{number} / 03</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
      <section className="section showcase"><div className="section-heading"><span className="eyebrow">Your story, in your hands</span><h2>Here’s the story we found.</h2><p>Take a look before we make your film. Change a scene, find a new image or try a different feeling.</p><Link className="text-link showcase-link" href="/create">Let’s shape the story <span aria-hidden="true">→</span></Link></div><div className="showcase-board" aria-hidden="true"><div className="board-top"><span>NORTHLINE.STUDIO / YOUR STORY</span><span>00:30 · 16:9</span></div><div className="board-scenes"><div className="board-scene">01 / THE HOOK</div><div className="board-scene">02 / THE STORY</div><div className="board-scene">03 / THE PRODUCT</div></div><div className="board-timeline"><i /><i /><i /></div></div></section>
      <section className="section format-section"><div className="section-heading"><span className="eyebrow">Ready for wherever you share</span><h2>Where will your film live?</h2><p>Choose a place to start. You can make another version for somewhere else, too.</p></div><div className="format-showcase"><div className="format-copy"><div><b>16:9</b><span>Wide · YouTube and web</span></div><div><b>9:16</b><span>Tall · Reels and Shorts</span></div><div><b>1:1</b><span>Square · Social and product</span></div><div><b>4:5</b><span>Tall · Social feeds</span></div></div><div className="format-frames" aria-hidden="true"><div className="format-frame landscape"><span>YOUR STORY / 16:9</span></div><div className="format-frame portrait"><span>YOUR STORY / 9:16</span></div><div className="format-frame square"><span>YOUR STORY / 1:1</span></div></div></div></section>
      <section className="section versions-section"><div className="versions-copy"><span className="eyebrow">There isn’t just one way to tell it</span><h2>Try a feeling that sounds like you.</h2><p>Change the words, voice or pace. Keep the story you started and see where another direction takes it.</p><Link href="/create" className="button button-light">Try another direction <span aria-hidden="true">→</span></Link></div><div className="version-list"><div><span>01</span><b>Thoughtful and unhurried</b><small>EDITORIAL · WARM VOICE</small></div><div><span>02</span><b>Bright and full of energy</b><small>LIVELY · QUICKER PACE</small></div><div><span>03</span><b>Simple, with every detail in focus</b><small>PRODUCT STORY · QUIET</small></div></div></section>
      <section className="section usecase-section"><div className="section-heading"><span className="eyebrow">For the people behind the website</span><h2>Whatever you’ve made, there’s a story in it.</h2></div><div className="usecase-list"><span>Independent brands</span><span>Marketing teams</span><span>Creative studios</span><span>Online shops</span><span>Growing products</span><span>Independent creators</span></div></section>
      <section className="section library-section"><div className="library-copy"><span className="eyebrow">Pick up where you left off</span><h2>Your stories, all in one place.</h2><p>Keep each project and its different directions close at hand.</p><Link href="/projects" className="text-link showcase-link">See my films →</Link></div><div className="library-preview"><div className="library-preview-head"><span>A FEW RECENT STORIES</span><span>TAKE A LOOK ↗</span></div><div className="library-row"><i className="library-thumb"/><span><b>Northline — brand film</b><small>northline.studio</small></span><em>30s · 16:9</em></div><div className="library-row"><i className="library-thumb second"/><span><b>Quietform — product story</b><small>quietform.co</small></span><em>15s · 9:16</em></div></div></section>
      <section className="section faq-section"><div className="section-heading"><span className="eyebrow">A few things you might wonder</span><h2>Good to know.</h2></div><div className="faq-list"><details><summary>Where does the story come from?</summary><p>SCORVIK looks at the words, images and details on your website to suggest a first story. You can change anything you like.</p></details><details><summary>Can I change things before my first look?</summary><p>Of course. Change the words, reorder scenes, choose a new image or try another feeling.</p></details><details><summary>Will I get a finished video?</summary><p>Not in this preview just yet. You can explore and save your story here. The download is a project file, not an MP4.</p></details><details><summary>Where are my stories saved?</summary><p>Your projects stay in this browser, on this device. They aren’t shared across devices yet.</p></details></div></section>
      <section className="section pricing-strip"><div><span className="eyebrow">Take your time and explore</span><h2>Your first story starts with a link.</h2><p>Try the preview with no account and no setup.</p></div><Link href="/pricing" className="button button-light">See what’s included <span aria-hidden="true">→</span></Link></section>
      <section className="section closing"><div><span className="eyebrow">Ready when you are</span><h2>Your website is a lovely place to start.</h2></div><Link href="/create" className="button button-lime">Start with my website <span aria-hidden="true">↗</span></Link></section>
      <footer className="footer"><Link className="brand" href="/"><span className="brand-mark" aria-hidden="true">S</span><span>SCORVIK</span></Link><span>Your story, in motion.</span><Link href="/projects">See my films →</Link></footer>
    </div>
  );
}
